---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moltbot-data
  namespace: apps
  labels:
    app.kubernetes.io/name: moltbot
    app.kubernetes.io/part-of: home-lab
    app.kubernetes.io/managed-by: kubectl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
