name: gap-analysis
description: "Validate story tasks against actual codebase - audit completed stories or validate before development"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
implementation_artifacts: "{config_source}:implementation_artifacts"
story_dir: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/gap-analysis"
instructions: "{installed_path}/instructions.xml"

# Variables
story_file: "" # User provides story file path or auto-discover
sprint_status: "{implementation_artifacts}/sprint-status.yaml"
project_context: "**/project-context.md"

standalone: true
