---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup
  namespace: data
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: home-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
