apiVersion: v1
kind: Pod
metadata:
  name: postgres-test-client
  namespace: apps
  labels:
    app.kubernetes.io/name: postgres-test-client
    app.kubernetes.io/component: test
    app.kubernetes.io/part-of: home-lab
spec:
  containers:
  - name: postgres-client
    image: registry-1.docker.io/bitnami/postgresql:latest
    command: ["sleep", "infinity"]
    env:
    - name: PGHOST
      value: "postgres-postgresql.data.svc.cluster.local"
    - name: PGPORT
      value: "5432"
    - name: PGUSER
      value: "postgres"
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-postgresql
          key: postgres-password
  restartPolicy: Never
