apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-consume-scans
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/part-of: home-lab
    app.kubernetes.io/component: consume-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=3
  nfs:
    server: 192.168.2.2
    path: /volume1/scans
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume-scans
  namespace: docs
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/part-of: home-lab
    app.kubernetes.io/component: consume-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: paperless-consume-scans
  resources:
    requests:
      storage: 10Gi
