---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-backup
  namespace: apps
  labels:
    app.kubernetes.io/name: openclaw
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: home-lab
    app.kubernetes.io/managed-by: kubectl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
